security:
  basic:
    enabled: false

#in order to print the default h2 log info
#logging:
#  level:
#    org:
#      hibernate: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:pocdb
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
  h2:
    console:
      enabled: true 
      path: /h2
      settings:
        web-allow-others: false